"""
SupplyVision – Phase 1: generate_sql.py
=========================================
Reads processed Parquet/CSV files and writes a complete
sample_data.sql file with INSERT statements for every table.

Output: sql/sample_data.sql

Usage:
    python src/etl/generate_sql.py
    python src/etl/generate_sql.py --limit 100   # 100 rows per table (demo mode)
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

import pandas as pd
from loguru import logger

Path("logs").mkdir(exist_ok=True)
logger.remove()
logger.add(sys.stdout, level="INFO", colorize=True,
           format="<green>{time:HH:mm:ss}</green> | <level>{level:<8}</level> | {message}")

PROCESSED_DIR = Path("data/processed")
SQL_DIR       = Path("sql")
SQL_DIR.mkdir(exist_ok=True)

# Tables in FK-safe insert order
TABLES = [
    ("dim_warehouses",  "warehouses_clean",  None),
    ("dim_suppliers",   "suppliers_clean",   None),
    ("dim_customers",   "customers_clean",   None),
    ("dim_products",    "inventory_clean",   [
        "Product_ID", "Product_Name", "Category",
        "Safety_Stock", "Reorder_Point", "Unit_Cost", "Unit_Price",
        "Warehouse_ID", "Supplier_ID",
    ]),
    ("fact_inventory",  "inventory_clean",   [
        "Product_ID", "Current_Stock", "Inventory_Value", "Stock_Status", "Last_Updated",
    ]),
    ("fact_orders",     "fact_orders_clean", [
        "Order_ID", "Product_ID", "Customer_ID", "Order_Date",
        "Year", "Month", "Quarter", "YearMonth", "YearQuarter",
        "WeekOfYear", "DayOfWeek", "Quantity", "Unit_Price", "Discount",
        "Revenue", "COGS", "Gross_Profit", "Gross_Margin_Pct",
        "Order_Status", "Sales_Channel", "Category",
        "Warehouse_ID", "Supplier_ID",
        "Shipment_Count", "Avg_Transit_Time", "Total_Transport_Cost", "Delayed_Shipments",
    ]),
    ("fact_logistics",  "logistics_clean",   [
        "Shipment_ID", "Order_ID", "Supplier_ID",
        "Ship_Date", "Delivery_Date", "Expected_Transit_Days", "Transit_Time",
        "Delay_Days", "Is_Delayed", "Transport_Cost", "Cost_Per_KG",
        "Carrier", "Delivery_Status", "Origin_Country", "Destination_Country",
        "Weight_KG", "Ship_Year", "Ship_Month", "Ship_Quarter", "Ship_YearMonth",
    ]),
]


def _load(stem: str) -> pd.DataFrame:
    p = PROCESSED_DIR / f"{stem}.parquet"
    if p.exists():
        return pd.read_parquet(p)
    c = PROCESSED_DIR / f"{stem}.csv"
    if c.exists():
        return pd.read_csv(c, low_memory=False)
    raise FileNotFoundError(
        f"File not found: {p} or {c}. Run: python pipeline.py --steps gen etl"
    )


def _escape_val(v) -> str:
    """Convert a Python value to a SQL literal string."""
    if v is None or (isinstance(v, float) and v != v):  # NaN check
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, date):
        return f"'{v}'"
    if isinstance(v, pd.Timestamp):
        return f"'{v.date()}'"
    # str fallback – escape single quotes
    s = str(v).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def table_to_inserts(
    table: str,
    df: pd.DataFrame,
    cols: list[str] | None,
    batch: int = 50,
) -> list[str]:
    if cols:
        available = [c for c in cols if c in df.columns]
        df = df[available].copy()
    else:
        df = df.copy()

    # Coerce types
    for col in df.columns:
        if hasattr(df[col].dtype, "freq"):  # PeriodDtype
            df[col] = df[col].astype(str)
    for col in df.select_dtypes(include="category").columns:
        df[col] = df[col].astype(str)
    for col in df.select_dtypes(include="datetime64[ns]").columns:
        df[col] = df[col].dt.date

    df = df.where(pd.notnull(df), None)
    col_list = ", ".join(df.columns)
    lines = [f"-- {table}: {len(df):,} rows"]

    for start in range(0, len(df), batch):
        chunk = df.iloc[start:start + batch]
        rows = []
        for _, row in chunk.iterrows():
            vals = ", ".join(_escape_val(v) for v in row)
            rows.append(f"    ({vals})")
        lines.append(
            f"INSERT INTO {table} ({col_list}) VALUES\n" +
            ",\n".join(rows) + ";"
        )

    return lines


def generate_sample_sql(limit: int | None = None) -> Path:
    out_path = SQL_DIR / "sample_data.sql"
    lines: list[str] = []

    lines += [
        "-- ============================================================",
        "-- SupplyVision – Sample Data",
        "-- Auto-generated by src/etl/generate_sql.py",
        f"-- Tables: {', '.join(t for t, _, _ in TABLES)}",
        "-- ============================================================",
        "",
        "USE supply_vision;",
        "SET FOREIGN_KEY_CHECKS = 0;",
        "",
    ]

    for table, stem, cols in TABLES:
        try:
            df = _load(stem)
        except FileNotFoundError as exc:
            logger.warning(f"Skipping {table}: {exc}")
            continue

        if limit:
            df = df.head(limit)

        logger.info(f"  Generating INSERTs: {table} ({len(df):,} rows) …")
        lines.append(f"\n-- ─── {table} {'─'*(50-len(table))}")
        lines.append(f"TRUNCATE TABLE {table};")
        lines += table_to_inserts(table, df, cols)

    lines += ["", "SET FOREIGN_KEY_CHECKS = 1;", "",
              "SELECT 'Sample data loaded successfully.' AS status;"]

    out_path.write_text("\n".join(lines), encoding="utf-8")
    size_kb = out_path.stat().st_size / 1024
    logger.success(f"Written: {out_path}  ({size_kb:,.0f} KB)")
    return out_path


def main():
    parser = argparse.ArgumentParser(description="SupplyVision – Generate sample_data.sql")
    parser.add_argument("--limit", type=int, default=None,
                        help="Limit rows per table (default: all)")
    args = parser.parse_args()
    generate_sample_sql(limit=args.limit)


if __name__ == "__main__":
    main()
